Naming/PredicateName:
  NameWhitelist:
    - is_enabled?

Metrics/LineLength:
  Max: 120

Style/RedundantSelf:
  Enabled: false
Style/PreferredHashMethods:
  Enabled: false
Style/StringLiterals:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false
